from texas import Card

car_map = [
    Card(2, 'A'),
    Card(3, 'A'),
    Card(4, 'A'),
    Card(5, 'A'),
    Card(6, 'A'),
    Card(7, 'A'),
    Card(8, 'A'),
    Card(9, 'A'),
    Card(10, 'A'),
    Card(11, 'A'),
    Card(12, 'A'),
    Card(13, 'A'),
    Card(14, 'A'),

    Card(2, 'B'),
    Card(3, 'B'),
    Card(4, 'B'),
    Card(5, 'B'),
    Card(6, 'B'),
    Card(7, 'B'),
    Card(8, 'B'),
    Card(9, 'B'),
    Card(10, 'B'),
    Card(11, 'B'),
    Card(12, 'B'),
    Card(13, 'B'),
    Card(14, 'B'),

    Card(2, 'C'),
    Card(3, 'C'),
    Card(4, 'C'),
    Card(5, 'C'),
    Card(6, 'C'),
    Card(7, 'C'),
    Card(8, 'C'),
    Card(9, 'C'),
    Card(10, 'C'),
    Card(11, 'C'),
    Card(12, 'C'),
    Card(13, 'C'),
    Card(14, 'C'),

    Card(2, 'D'),
    Card(3, 'D'),
    Card(4, 'D'),
    Card(5, 'D'),
    Card(6, 'D'),
    Card(7, 'D'),
    Card(8, 'D'),
    Card(9, 'D'),
    Card(10, 'D'),
    Card(11, 'D'),
    Card(12, 'D'),
    Card(13, 'D'),
    Card(14, 'D'),
]
